### ISSUE TITLE
A Prefrontal Cortex-inspired Architecture for Planning in Large Language Models

### ISSUE THREAD

**Issue by KnutJaegersberg** [open-thought/system-2-research#22]
A Prefrontal Cortex-inspired Architecture for Planning in Large Language Models

also a useful paper on LLM planning

https://arxiv.org/abs/2310.00194

**Comment by KnutJaegersberg** [comment]
another useful hierarchy 
![image](https://github.com/user-attachments/assets/52e24a0f-ddbe-45ef-bd33-3e98cb5d86d4)

**Comment by andreaskoepf** [comment]
Nice one! Do you want to create a PR yourself or should I add it?

**Comment by andreaskoepf** [comment]
Added via https://github.com/open-thought/system-2-research/commit/9fd233edf4e1ddb0769c17eb44006c6865d18b59. Will review the other ones you submitted tonight.
