### ISSUE TITLE
Conceptual Framework for Autonomous Cognitive Entities

### ISSUE THREAD

**Issue by KnutJaegersberg** [open-thought/system-2-research#24]
Conceptual Framework for Autonomous Cognitive Entities

this is the cognitive architecture by Shapiro, also a good overview of important concepts. He's been heavily invested into thinking about this stuff since quite a while. 

https://arxiv.org/abs/2310.06775

**Comment by KnutJaegersberg** [comment]
you know this one: 
![image](https://github.com/user-attachments/assets/031a71fa-8fd6-4479-9b92-e85374c60fdc)

**Comment by KnutJaegersberg** [comment]
I think it gives a good overview of concepts relevant for coordination with system 2

**Comment by ehartford** [comment]
This is nice

**Comment by andreaskoepf** [comment]
@KnutJaegersberg thanks a lot, added ACE under the cognitive architectures.
