### ISSUE TITLE
Add Neurallambda

### ISSUE THREAD

**Issue by freckletonj** [open-thought/system-2-research#6]
I'm working on a neural lambda-calculus compiler, and less crazy things, here: https://github.com/neurallambda/neurallambda

I'm be happy to answer questions, or connect.

**Comment by freckletonj** [comment]
You might also find this relevant, a repository of reasoning datasets: https://github.com/neurallambda/awesome-reasoning

**Comment by andreaskoepf** [comment]
Thanks for sharing the link to your differentiable lambda calculus project. If you like you can discuss with us in the `#open-thought` channel of the YK discord server: https://ykilcher.com/discord

I personally would for example be interested how you envision the combination of your lib with existing models and if you could give a few examples where differential lambda calculus really shines and helps to reason...

**Comment by freckletonj** [comment]
@andreaskoepf It's still an open research project. The neurallambda compiler piece does indeed work (without even training), and is backproppable, but it is TBD if there's a pay off to this approach. I believe that "reasoning" is the final hurdle in AI, and that a turing machine is the way to confer reasoning onto AI.

I'll join the discord!
